// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ConvertBase64Image(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function DeleteConvertedImage(arg1:string):Promise<void>;

export function GetConvertedImageBase64(arg1:string):Promise<string>;

export function GetConvertedImages():Promise<Array<backend.ConvertedImage>>;
