// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertBase64Image(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['ImageService']['ConvertBase64Image'](arg1, arg2, arg3, arg4);
}

export function DeleteConvertedImage(arg1) {
  return window['go']['backend']['ImageService']['DeleteConvertedImage'](arg1);
}

export function GetConvertedImageBase64(arg1) {
  return window['go']['backend']['ImageService']['GetConvertedImageBase64'](arg1);
}

export function GetConvertedImages() {
  return window['go']['backend']['ImageService']['GetConvertedImages']();
}
